services:
  client-dev:
    image: node:18
    working_dir: /app/client
    volumes:
      - ./:/app:Z
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["sh","-c","npm install --prefix client --silent && npm run dev --prefix client -- --host 0.0.0.0"]
    depends_on:
      - app
    restart: unless-stopped

  server-dev:
    image: node:18
    working_dir: /app/server
    volumes:
      - ./:/app:Z
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - ELASTIC_URL=http://elasticsearch:9200
    command: ["sh","-c","npm install --prefix server --silent && npm run dev --prefix server"]
    depends_on:
      - elasticsearch
    restart: unless-stopped

# Notes:
# - This override is intended for local development using podman-compose.
# - It mounts the repository into the containers so file changes trigger Vite and ts-node-dev reloads.
# - The client is started with `--host 0.0.0.0` so the dev server is reachable from the host machine.
